import pygame
from pygame.locals import *
from coreClasses import pyGEnv, myPalette
import random
import math
from datetime import date, datetime

# 1. Setup Environment
WIDTH, HEIGHT = 1000, 1000
BKCOLOR = (20, 20, 25) # Deep midnight
pyG1 = pyGEnv()
pyG1.createScreen(WIDTH, HEIGHT, BKCOLOR)
mypal = myPalette('TheBlues')

def draw_moire_texture(surface, x, y, w, h, color):
    """
    Renders a high-density line pattern within a cell.
    The 'Moiré' effect is generated by varying line density and angles.
    """
    num_lines = random.randint(15, 40)
    angle_mode = random.choice(['horizontal', 'vertical', 'diagonal', 'crosshatch'])
    
    # Draw high-frequency lines to create interference patterns
    for i in range(num_lines):
        alpha = int(remap(i, 0, num_lines, 50, 200))
        line_color = (*color[:3], alpha) # Maintain palette but vary transparency
        
        if angle_mode == 'horizontal':
            py = y + (i * (h / num_lines))
            pygame.draw.line(surface, line_color, (x, py), (x + w, py), 1)
        elif angle_mode == 'vertical':
            px = x + (i * (w / num_lines))
            pygame.draw.line(surface, line_color, (px, y), (px, y + h), 1)
        elif angle_mode == 'diagonal':
            # Slanted lines that create complex intersections when adjacent
            pygame.draw.line(surface, line_color, (x + (i * w/num_lines), y), (x, y + (i * h/num_lines)), 1)
            pygame.draw.line(surface, line_color, (x + w, y + (i * h/num_lines)), (x + (i * w/num_lines), y + h), 1)

def recursive_grid(surface, x, y, w, h, level):
    """
    Subdivides the space and decides when to render a texture.
    """
    max_level = 4
    # Probability of stopping recursion increases with depth
    if level > random.randint(1, max_level):
        color = random.choice(mypal.pal)
        draw_moire_texture(surface, x, y, w, h, color)
        # Draw a subtle border to define the recursive structure
        pygame.draw.rect(surface, (255, 255, 255, 30), (x, y, w, h), 1)
    else:
        # Split into 4 quadrants
        nw = w / 2
        nh = h / 2
        recursive_grid(surface, x, y, nw, nh, level + 1)
        recursive_grid(surface, x + nw, y, nw, nh, level + 1)
        recursive_grid(surface, x, y + nh, nw, nh, level + 1)
        recursive_grid(surface, x + nw, y + nh, nw, nh, level + 1)

def remap(value, start1, stop1, start2, stop2):
    return start2 + (stop2 - start2) * ((value - start1) / (stop1 - start1))

def main():
    running = True
    while running:
        pyG1.screen.fill(BKCOLOR)
        
        # Create a transparent overlay for the textures
        overlay = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
        recursive_grid(overlay, 50, 50, WIDTH-100, HEIGHT-100, 0)
        
        pyG1.screen.blit(overlay, (0, 0))
        pygame.display.flip()
        
        # Pause to view the composition
        pygame.time.delay(2000)
        
        for event in pygame.event.get():
            if event.type == QUIT:
                running = False
            if event.type == KEYDOWN and event.key == pygame.K_s:
                dt = datetime.now()
                pygame.image.save(pyG1.screen,'images/' + 'moiregrid_' + dt.strftime("%Y%m%d_%H%M%S") + '.jpg')
    pygame.quit()

if __name__ == "__main__":
    main()